trigger:
 branches:
  include:
    - main
 paths:
   exclude:
     - pipelines
     - logicapps

name: Deploy Simple Bicep to RG - $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)-$(Hours)$(Minutes)$(Seconds)   

variables:
  vmImageName: 'ubuntu-latest'
  devAzureServiceConnection: 'russ-airs'
  testAzureServiceConnection: 'russ-airs'
  prodAzureServiceConnection: 'russ-airs'
  location: 'uksouth'
  resourceGroupName: 'rg-simple-cicd'
  logicAppName: 'logicapp-hello-world'

stages:
- stage: 'dev_deploy'
  displayName: 'Deploy to Dev Environment Stage'
  jobs:
  - deployment: 'dev_deploy_bicep'
    displayName: 'Deploy to Dev Environment Deployment'
    pool:
      vmImage: $(vmImageName)
    environment: 
      name: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: 'Azure CLI Create RG and deploy bicep'
            inputs:
              azureSubscription: $(devAzureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                ls -R
                az --version
                cd bicep
                az group create --name $(resourceGroupName) --location $(location)
                az deployment group create --name infradeploy -g $(resourceGroupName) --template-file fnapp.bicep